name: Release Lifecycle

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    types:
      - opened
    branches:
      - 'feature/**'

jobs:
  release:
    name: Release Lifecycle
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          version: 14

      - name: Configuring Git user email
        run: git config --global user.email "actions@github.com"

      - name: Configuring Git user name
        run: git config --global user.name "Github Action Bot"

      - name: Installing packages
        run: yarn install

      - name: Release
        run: yarn release
