name: Release Lifecycle

on:
  pull_request:
    types:
      - opened
    branches:
      - 'feature/**'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Bumping the release .....'"
      - run: yarn release
